### ISSUE TITLE
Time taken to train the model from scratch

### ISSUE THREAD

**Issue by ishanisri** [AI-secure/InfoBERT#1]
Hi, this is more of a question than an issue. How long does it take for the model to train approximately on a single GPU without batch size of 16?

Thanks

**Comment by boxin-wbx** [comment]
Thanks for your interest in our work. It usually took 8 hours to train InfoBERT with the `anli_full` setting for 3 epochs given 8 GPUs. With a single GPU, I am afraid the training time is approximately 8*8=64 hours.

**Comment by ishanisri** [comment]
Thank you for the quick reply. This does seem like a lot and unfortunately, it might not be possible for me as a student to get hold of hardware with 8 GPUs. Do you have any suggestions on a smaller model to train or a smaller dataset which is a sample representation of ANLI?

Thanks

**Comment by boxin-wbx** [comment]
1. Maybe you can try adapt the code to `roberta-base` or `bert-base` to reduce the memory consumption.
2. You can try to run the code without adversarial training, which will save 30~60% training time.
3. You can try to train your model with benign data only (SNLI + MNLI), and report its robust accuracy over ANLI test set.
