### ISSUE TITLE
How are A1,A2, A3 scores calculated from r1,r2,r3 test results?

### ISSUE THREAD

**Issue by ishanisri** [AI-secure/InfoBERT#2]
The results of evaluation show here in the README file vs the ones in the paper are based on different metrics. The paper shows A1,A2,A3 scores along with accuracy on adv-MNLi, adv-SNLi etc, whereas running the evaluation here shows us accuracy roundwise of both tests and dev data. Is there any formula to calculate the A1,A2,A3 scores from the test scores mentioned in the repo? 

Thanks in advance for the help :)

**Comment by boxin-wbx** [comment]
You may find A1, A2, A3 test scores in the log, which are respectively anli-r1-test, anli-r2-test, anli-r3-test.

**Comment by ishanisri** [comment]
Ah okay, this helped a lot, thanks!
