### ISSUE TITLE
Runtime Error - "Distributed package doesn't have NCCL" when running runexp

### ISSUE THREAD

**Issue by eaberman** [AI-secure/InfoBERT#3]
When I run `source setup.sh && runexp      anli-full      infobert     roberta-large          2e-5        32             128              -1                1000          42           1e-5         5e-3            6       0.1    0       4e-2         8e-2        0        3         5e-3      0.5     0.9` as specified in the README in the ANLI directory, I encounter a `RuntimeError: Distributed package doesn't have NCCL built in` message.

Do you have any advice on how to fix this?

Thank you! I really admire your work.

**Comment by boxin-wbx** [comment]
NCCL is usually installed together with PyTorch. You may try to reinstall PyTorch with conda.

**Comment by eaberman** [comment]
Thank you! I was able to fix this and get it running.
